
create-image:
	klayout -z -r klayout_image.py -rd input=FMD_QNC_greyhound_ihp.oas -rd output_image=FMD_QNC_greyhound_ihp.png
	convert FMD_QNC_greyhound_ihp.png -resize 25% FMD_QNC_greyhound_ihp_small.png
.PHONY: create-image

